import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { VitePWA } from "vite-plugin-pwa";

// Our Little World — Vite config.
// Keeps the existing PWA behavior (manifest, icons, offline shell) from the
// old sw.js/manifest.json, now generated by vite-plugin-pwa instead of a
// hand-written service worker.
export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: "autoUpdate",
      workbox: {
        cleanupOutdatedCaches: true,
        clientsClaim: true,
        skipWaiting: true
      },
      includeAssets: ["assets/icons/icon-192.png", "assets/icons/icon-512.png"],
      manifest: {
        name: "Our Little World",
        short_name: "Our Little World",
        description: "a little place that belongs to us",
        theme_color: "#160b10",
        background_color: "#0c0709",
        display: "standalone",
        start_url: "/",
        icons: [
          { src: "assets/icons/icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "assets/icons/icon-512.png", sizes: "512x512", type: "image/png" }
        ]
      }
    })
  ],
  server: { port: 5173 }
});
